# Supabase 設定 (可在專案的 Project Settings -> API 中找到)
SUPABASE_URL = "https://btnlbempdnwpaeymrghc.supabase.co"
SUPABASE_KEY = "sb_publishable_wOsiW44WSKxHRWDd8FBATw_0UrSIsrT"
# Telegram Bot 設定 (透過 BotFather 取得 Token，並透過 @userinfobot 等工具取得你的 Chat ID)
TELEGRAM_BOT_TOKEN = "8870487328:AAEiWcNTLwCdCGcWn_Ce0MoEfOumsKmyZSo"
CHAT_ID = "7070343714"